<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Drusilla canaliculata</title>

>GBCL0857-06|AJ293035|Drusilla canaliculata|
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------GCTCATGCTTTCATTATAATTTTCTTTATAGTTATGCCTATTGTAATTGGTGGATTCGGAAATTGATTAATTCCACTAATA---TTAGGAGCCCCTGATATAGCTTTCCCACGAATAAACAATATGAGATTTTGATTATTACCCCCCTCTTTAAGCCTTCTTTTAATAAGAAGAATGGTTGAAAGAGGTGCTGGAACAGGATGAACAGTTTATCCTCCTTTATCATCAAATATTGCACATGGAGGATCTTCAGTTGATTTA---GCTATTTTTAGTCTACATTTAGCTGGTATTTCTTCAATTTTAGGAGCTGTAAATTTTATTTCAACTGTAATTAATATACGATCAACTGGAATTTCATTTGATCGTATACCTTTATTTGTTTGATCAGTTGCTATTACAGCATTATTATTACTACTATCCTTACCAGTATTAGCAGGA---GCTATTACAATACTTTTAACTGACCGAAACTTAAATACTTCCTTTTTTGACCCTGCTGGAGGTGGTGACCCAATTTTATACCAACATTTATTTTGATTTTTTGGTCATCCAGAAGTTTACATTTTAATTCTACCAGGATTTGGAATAATTTCTCATATTATTAGCCAAGAAAGAGGTAAAAAG---GAAACATTTGGGACCCTTGGAATAATTTATGCTATAATAACAATTGGATTATTAGGATTTGTTGTTTGAGCTCATCATATATTCACAGTAGGAATAG
>GBCL15134-13|GQ980874|Drusilla canaliculata|
---------------------------------------ACCTTATATTTCATTTTTGGAGCATGAGCAGGAATAGTTGGAACATCTTTA---AGACTATTAATTCGAGCTGAATTAGGTAATCCAGGTTCATTAATTGGAGAC---GACCAAATTTATAATGTTATTGTTACAGCTCATGCTTTCATTATAATTTTCTTTATAGTTATGCCTATTGTAATTGGTGGATTCGGAAATTGATTAATTCCACTAATA---TTAGGAGCCCCTGATATAGCTTTCCCACGAATAAACAATATGAGATTTTGATTATTACCCCCCTCTTTAAGCCTTCTTTTAATAAGAAGAATGGTTGAAAGAGGTGCTGGAACAGGATGAACAGTTTATCCTCCTTTATCATCAAATATTGCACATGGAGGATCTTCAGTTGATTTA---GCTATTTTTAGTCTACATTTAGCTGGTATTTCTTCAATTTTAGGAGCTGTAAATTTTATTTCAACTGTAATTAATATACGATCAACTGGAATTTCATTTGATCGTATACCTTTATTTGTTTGATCAGTTGCTATTACAGCATTATTATTACTACTATCCTTACCAGTATTAGCAGGA---GCTATTACAATACTTTTAACTGACCGAAACTTAAATACTTCCTTTTTTGACCCTGCTGGAGGTGGTGACCCAATTTTATACCAACATTTATTTTGATTTTTTGGTCATCCAGAAGTTTACATTTTAATTCTACCAGGATTTGGAATAATTTCTCATATTATTAGCCAAGAAAGAGGTAAAAAG---GAAACATTTGGGACCCTTGGAATAATTTATGCTATAATAACAATTGGATTATTAGGGTTTGTTGTTTGAGCTCATCATATATTCACAGTAGGAATAG
>GBCL15135-13|GQ980873|Drusilla canaliculata|
------------------------------------------------TTCATTTTTGGAGCATGAGCAGGAATAGTTGGAACATCTTTA---AGACTATTAATTCGAGCTGAATTAGGTAATCCAGGTTCATTAATTGGAGAC---GACCAAATTTATAATGTTATTGTTACAGCTCATGCTTTCATTATAATTTTCTTTATAGTTATGCCTATTGTAATTGGTGGATTCGGAAATTGATTAATTCCACTAATA---TTAGGAGCCCCTGATATAGCTTTCCCACGAATAAACAATATGAGATTTTGATTATTACCCCCCTCTTTAAGCCTTCTTTTAATAAGAAGAATGGTTGAAAGAGGTGCTGGAACAGGATGAACAGTTTATCCTCCTTTATCATCAAATATTGCACATGGAGGATCTTCAGTTGATTTA---GCTATTTTTAGTCTACATTTAGCTGGTATTTCTTCAATTTTAGGAGCTGTAAATTTTATTTCAACTGTAATTAATATACGATCAACTGGAATTTCATTTGATCGTATACCTTTATTTGTTTGATCAGTTGCTATTACAGCATTATTATTACTACTATCCTTACCAGTACTAGCAGGA---GCTATTACAATACTTTTAACTGACCGAAACTTAAATACTTCCTTTTTTGACCCTGCTGGAGGTGGTGACCCAATTTTATACCAACATTTATTTTGATTTTTTGGTCATCCAGAAGTTTACATTTTAATTCTACCAGGATTTGGAATAATTTCTCATATTATTAGCCAAGAAAGAGGTAAAAAG---GAAACATTTGGGACCCTTGGAATAATTTATGCTATAATAACAATTGGATTATTAGGGTTTGTTGTTTGAGCTCATCATATATTCACAGTAGGAATAG
>RBINA069-13|BIOUG07924-F09|Drusilla canaliculata|
---------------------------------------ACCTTATATTTCATTTTTGGAGCATGAGCAGGAATAGTTGGAACATCTTTA---AGACTATTAATTCGAGCTGAATTAGGTAATCCAGGTTCATTAATTGGAGAC---GACCAAATTTATAATGTTATTGTTACAGCTCATGCTTTCATTATAATTTTCTTTATAGTTATGCCTATTGTAATTGGTGGATTCGGAAATTGATTAATTCCACTAATA---TTAGGAGCCCCTGATATAGCTTTCCCACGAATAAACAATATGAGATTTTGATTATTACCCCCCTCTTTAAGCCTTCTTTTAATAAGAAGAATGGTTGAAAGAGGTGCTGGAACAGGATGAACAGTTTATCCTCCTTTATCATCAAATATTGCACATGGAGGATCTTCAGTTGATTTA---GCTATTTTTAGTCTACATTTAGCTGGTATTTCTTCAATTTTAGGAGCTGTAAATTTTATTTCAACTGTAATTAATATACGATCAACTGGAATTTCATTTGATCGTATACCTTTATTTGTTTGATCAGTTGCTATTACAGCATTATTATTACTACTATCCTTACCAGTATTAGCAGGA---GCTATTACAATACTTTTAACTGACCGA----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




</head>
<body>

</body>
</html>